name: Metricsp

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: JNX03
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Bangkok
          plugin_followup: yes
          plugin_languages: yes
          plugin_lines: yes
