name: Metrics

on:
  # Schedule updates every 8 hours
  schedule:
    - cron: "0 */8 * * *"
  # Manual trigger and on push to main/master
  workflow_dispatch:
  push:
    branches: ["master", "main"]

jobs:
  generate_profile:
    runs-on: ubuntu-latest

    steps:
      # ───────────── LEFT PANEL (base + activity + community + languages + habits + rss) ─────────────
      - name: left
        uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          # ← replace with your “left” Gist ID (where metrics.svg will be pushed)
          committer_gist: <YOUR_LEFT_GIST_ID>

          # core settings
          user: JNX03
          template: classic
          config_timezone: Asia/Shanghai

          # panels
          base: header, activity, community
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_ignored: 'html, css, Jupyter Notebook'
          plugin_languages_details: lines, percentage
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_aliases: 'RenderScript:Rust'
          commits_authoring: JNX03
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_rss: yes
          plugin_rss_source: https://blog.JNX03.com/atom.xml   # ← update to your RSS
          plugin_rss_limit: 4

          # layout tweaks
          config_padding: 0, 8 + 11%
          config_order: base.header, base.activity+community, languages, habits, rss

      # ───────────── RIGHT PANEL (achievements + wakatime) ─────────────
      - name: right
        uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          # ← replace with your “right” Gist ID
          committer_gist: <YOUR_RIGHT_GIST_ID>

          user: JNX03
          template: classic
          config_timezone: Asia/Shanghai

          plugin_achievements: yes
          plugin_achievements_limit: 8

          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

          config_padding: 0, 8 + 11%
          config_order: achievements, wakatime

      # ───────────── GITHUB‑SNAKE (fun “snake game” footer) ─────────────
      - name: snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-snake.svg?palette=github-light
            github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: deploy snake to gist
        uses: exuanbo/actions-deploy-gist@v1.1.4
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          gist_id: <YOUR_SNAKE_GIST_ID>
          gist_file_name: github-snake.svg
          file_path: github-snake.svg

      - name: deploy dark snake to gist
        uses: exuanbo/actions-deploy-gist@v1.1.4
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          gist_id: <YOUR_SNAKE_GIST_ID>
          gist_file_name: github-snake-dark.svg
          file_path: github-snake-dark.svg
